name: TooHuman1SE
theme: jekyll-theme-midnight
title: Too Human 1 Save Editor
permalink: index.md

repository: https://github.com/xJam-es/TooHuman1SE

twitter:
  username: xJam_es
  
logo: /img/logo-2x.png
